GET http://{{domain_name}}/{{api-version1}}/users
Content-Type: application/json

###
POST http://{{domain_name}}/{{api-version1}}/users
Content-Type: application/json

{
  "name": "jveux89",
  "email": "email@example.com",
  "password": "averysafepassword"
}
