openapi: 3.0.1
info:
  title: Bugtracker API
  description: Bugtracker API project for testing purposes only
  license:
    name: MIT License (MIT)
  version: 0.0.1
  contact:
    email: devulogijrp.github@gmail.com
servers:
  - url: http://localhost:8080
paths:
  /users:
    summary: Returns a list of users
    description: User operations
    get:
      description: Get all users
      operationId: getAllUsers
      content:
        application/json:
          schema:
            type: arrayå
            items:
              properties:
                _id:
                  type: string
                  example: 5f9f1c9b9b9b9b9b9b9b9b9b
                username:
                  type: string
                  example: jveux89
                password:
                  type: string
                  example: 5de3884ca729a97bfd30f178c695c134e0196b755133d6252fc42edeba1e7ea971cf2da75a458a6e3b9021ae91799689aa5b180f2857b4480cf557c2649eda58
                email:
                  type: string
                  example: jveux89@example.com
                role:
                  type: string
                  example: user
                bugs:
                  type: array
                  items:
                    properties:
                      _id:
                        type: string
                        example: 5f9f1c9b9b9b9b9b9b9b9b9b
                      title:
                        type: string
                        example: Bug title
                      description:
                        type: string
                        example: Bug description
                      status:
                        type: string
                        example: open
                      priority:
                        type: string
                        example: low
                      created_at:
                        type: string
                        example: 2020-10-29T12:00:00.000Z
                      updated_at:
                          type: string
                          example: 2020-10-29T12:00:00.000Z
                created_at:
                    type: string
                    example: 2020-10-30T12:00:00.000Z
                updated_at:
                    type: string
                    example: 2020-10-30T12:00:00.000Z
  /users/{id}:
    description: Get a user by id
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 5f9f1c9b9b9b9b9b9b9b9b9b
          required: true
          description: Numeric ID of the user to get
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  _id:
                    type: string
                    example: 5f9f1c9b9b9b9b9b9b9b9b9b
                  username:
                    type: string
                    example: jveux89
                  password:
                    type: string
                    example: 5de3884ca729a97bfd30f178c695c134e0196b755133d6252fc42edeba1e7ea971cf2da75a458a6e3b9021ae91799689aa5b180f2857b4480cf557c2649eda58
                  email:
                    type: string
                    example: jveux89@example.com
                  role:
                    type: string
                    example: user
                  bugs:
                    type: array
                    items:
                      properties:
                        _id:
                          type: string
                          example: 5f9f1c9b9b9b9b9b9b9b9b9b
                        title:
                          type: string
                          example: Bug title
                        description:
                          type: string
                          example: Bug description
                        status:
                          type: string
                          example: open
                        priority:
                          type: string
                          example: low
                        created_at:
                          type: string
                          example: 2020-10-29T12:00:00.000Z
                        updated_at:
                          type: string
                          example: 2020-10-29T12:00:00.000Z
                  created_at:
                    type: string
                    example: 2020-10-30T12:00:00.000Z
                  updated_at:
                    type: string
                    example: 2020-10-30T12:00:00.000Z
