openapi: 3.0.1
info:
  title: Bugtracker API
  description: Bugtracker API project for testing purposes only
  license:
    name: MIT License (MIT)
  version: 0.0.1
  contact:
    email: devulogijrp.github@gmail.com
servers:
  - url: http://localhost:8080
paths:
  /register:
    post:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
