name: "Test Manual Workflow"

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Your GitHub username'
        required: true
      reason:
        description: 'Why are you running this workflow manually?'
        required: true
        default: 'I am running tests before implementing an automated workflow'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo "User ${{ github.event.inputs.username }}"
          echo "Because ${{ github.event.inputs.reason }}"
